#!/usr/bin/python

import sys
import subprocess

cmd = "brightnessctl"
arg_get = "g"
arg_set = "s"
arg_max = "m"

def print_help():
    print("-- usage --")
    print("brightness increase")
    print("brightness decrease")

def clamp_light(value):
    return min(1, max(.01, value))

def set_light(value):
    value = clamp_light(value)
    subprocess.call([cmd, arg_set, str(value * float(subprocess.check_output([cmd, arg_max])))])

if len(sys.argv) != 2:
    print_help()
    print("error: you must provide exactly 1 argument", file=sys.stderr)
    exit(1)

factor = 2
light = float(subprocess.check_output([cmd, arg_get])) / float(subprocess.check_output([cmd, arg_max]))
liigt = light
light = clamp_light(light)
arg = sys.argv[1]

if arg == "increase":
    set_light(light * factor)
elif arg == "decrease":
    set_light(light / factor)
else:
    print_help()
    print("error: unknown argument")
    exit(1)
